import { BUILDING_BLOCK_UI_STATES } from "../types.js";
import type { BuildingBlockManifest } from "../types.js";
import {
  REGISTRY_BUSINESS_BLOCK_ID,
  REGISTRY_BUSINESS_VERSION,
} from "./config.js";

export const registryBusinessManifest: BuildingBlockManifest = {
  id: REGISTRY_BUSINESS_BLOCK_ID,
  version: REGISTRY_BUSINESS_VERSION,
  name: "Business Registry",
  description:
    "The workspace’s fictional legal entity, locations, firmographics, and compliance metadata — not a second CRM of clients.",
  category: "foundation",
  lifecycleStatus: "available",
  supportedBusinessModels: [
    "creative_marketing_agency",
    "digital_studio",
    "professional_services",
  ],
  businessProblemsSolved: [
    "Know the registered company that owns this workspace",
    "Keep offices, signatories, and renewals in one governed place",
    "Answer registration and compliance questions with cited records",
  ],
  recommendationTriggers: [
    "industry:agency",
    "need:legal-entity",
    "verified-fact:registered-company",
    "operating-profile:firmographics",
  ],
  dependencies: [],
  incompatibleBlocks: [],
  routes: [
    {
      path: "/admin/settings/business",
      title: "Business Registry",
      permission: "organization.read",
    },
    {
      path: "/admin/building-blocks/registry.business",
      title: "Business Registry configuration",
      permission: "building_block.configure",
    },
  ],
  navigation: [
    {
      id: "business-registry",
      label: "Business",
      href: "/admin/settings/business",
      appearsWhen: "active",
    },
  ],
  uiEntryPoints: [
    "identity",
    "registration",
    "locations",
    "firmographics",
    "ownership",
    "tax-banking",
    "insurance",
    "policies",
    "renewals",
    "audit",
  ],
  configurationSchemaVersion: 1,
  ownedEntities: [
    "organization.profile",
    "organization.location",
    "organization.compliance_record",
    "organization.bank_mask",
    "organization.signatory",
  ],
  referencedSharedEntities: [
    "workspace",
    "workspace.member",
    "organization",
  ],
  commands: [
    {
      id: "update_business_profile",
      permission: "organization.update_profile",
      sideEffect: "write",
    },
    {
      id: "add_location",
      permission: "location.manage",
      sideEffect: "write",
    },
    {
      id: "update_location",
      permission: "location.manage",
      sideEffect: "write",
    },
    {
      id: "archive_location",
      permission: "location.manage",
      sideEffect: "write",
    },
    {
      id: "change_primary_location",
      permission: "location.manage",
      sideEffect: "protected-write",
    },
    {
      id: "update_firmographics",
      permission: "organization.update_profile",
      sideEffect: "write",
    },
    {
      id: "add_registration_document",
      permission: "registry.document.manage",
      sideEffect: "write",
    },
    {
      id: "update_renewal_dates",
      permission: "registry.document.manage",
      sideEffect: "write",
    },
    {
      id: "assign_compliance_owner",
      permission: "registry.compliance.manage",
      sideEffect: "write",
    },
  ],
  queries: [
    { id: "get_business_profile", permission: "organization.read" },
    { id: "get_business_registration", permission: "organization.read" },
    { id: "list_business_locations", permission: "location.read" },
    { id: "get_business_firmographics", permission: "organization.read" },
    { id: "list_authorised_signatories", permission: "organization.read" },
    { id: "list_expiring_business_documents", permission: "organization.read" },
    { id: "list_compliance_obligations", permission: "organization.read" },
  ],
  deterministicRules: [
    "demo-clock-renewals",
    "declared-versus-computed-metrics",
    "single-canonical-organization",
    "demo-prefixed-identifiers",
  ],
  kpis: ["active-locations", "documents-due-30", "documents-due-90"],
  permissions: [
    "organization.read",
    "organization.update_profile",
    "location.read",
    "location.manage",
    "registry.document.manage",
    "registry.tax.manage",
    "registry.signatory.manage",
    "registry.compliance.manage",
    "building_block.read",
    "building_block.configure",
    "building_block.approve",
    "building_block.suspend",
  ],
  aiTools: [
    {
      name: "get_business_profile",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "get_business_registration",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "list_business_locations",
      permission: "location.read",
      sideEffect: "read",
    },
    {
      name: "get_business_firmographics",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "list_authorised_signatories",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "list_expiring_business_documents",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "list_compliance_obligations",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "explain_business_structure",
      permission: "organization.read",
      sideEffect: "read",
    },
    {
      name: "propose_business_profile_update",
      permission: "organization.update_profile",
      sideEffect: "propose",
    },
    {
      name: "propose_location_change",
      permission: "location.manage",
      sideEffect: "propose",
    },
  ],
  events: [
    { name: "business_profile.created", direction: "emitted" },
    { name: "business_profile.updated", direction: "emitted" },
    { name: "location.created", direction: "emitted" },
    { name: "location.updated", direction: "emitted" },
    { name: "location.archived", direction: "emitted" },
    { name: "primary_location.change_proposed", direction: "emitted" },
    { name: "registration_record.created", direction: "emitted" },
    { name: "registration_record.updated", direction: "emitted" },
    { name: "document.renewal_due", direction: "emitted" },
    { name: "compliance_owner.assigned", direction: "emitted" },
  ],
  integrationPoints: ["ask-flow", "audit", "module-registry"],
  seedDataProfile: "northstar-creative-registry-v1",
  supportedUiStates: [...BUILDING_BLOCK_UI_STATES],
  migrationVersion: "20260907000100",
  testRequirements: [
    "single-canonical-organization",
    "two-active-locations",
    "demo-prefix",
    "ein-scan",
    "seed-idempotency",
    "production-slug-rejected",
    "workspace-isolation",
    "permissions",
    "declared-versus-computed",
    "demo-clock-renewals",
    "ask-flow-evidence",
    "audit-events",
    "six-ui-states",
  ],
};
