import { BUILDING_BLOCK_UI_STATES } from "../types.js";
import type { BuildingBlockManifest } from "../types.js";
import { CRM_CORE_BLOCK_ID, CRM_CORE_VERSION } from "./config.js";

export const crmCoreManifest: BuildingBlockManifest = {
  id: CRM_CORE_BLOCK_ID,
  version: CRM_CORE_VERSION,
  name: "CRM Core",
  description:
    "Client organisations, contacts, relationship history, segments, and duplicate review.",
  category: "commercial",
  lifecycleStatus: "available",
  supportedBusinessModels: [
    "creative_marketing_agency",
    "digital_studio",
    "professional_services",
  ],
  businessProblemsSolved: [
    "Know who the clients are",
    "Keep relationship owners accountable",
    "Spot dormant and duplicate accounts",
  ],
  recommendationTriggers: [
    "industry:agency",
    "problem:client-tracking",
    "sales-process:relationship",
    "verified-fact:has-clients",
  ],
  dependencies: [],
  incompatibleBlocks: [],
  routes: [
    {
      path: "/admin/clients",
      title: "Client directory",
      permission: "client.read",
    },
    {
      path: "/admin/clients/:id",
      title: "Client 360",
      permission: "client.read",
    },
    {
      path: "/admin/clients/segments",
      title: "Segments",
      permission: "client.read",
    },
    {
      path: "/admin/clients/duplicates",
      title: "Duplicate review",
      permission: "crm.duplicate.propose",
    },
    {
      path: "/admin/building-blocks/crm.core",
      title: "CRM Core configuration",
      permission: "building_block.configure",
    },
  ],
  navigation: [
    {
      id: "clients",
      label: "Clients",
      href: "/admin/clients",
      appearsWhen: "active",
    },
    {
      id: "segments",
      label: "Segments",
      href: "/admin/clients/segments",
      appearsWhen: "active",
    },
    {
      id: "duplicates",
      label: "Duplicates",
      href: "/admin/clients/duplicates",
      appearsWhen: "active",
    },
  ],
  uiEntryPoints: [
    "directory",
    "client-360",
    "contacts",
    "timeline",
    "segments",
    "duplicate-queue",
    "configuration",
  ],
  configurationSchemaVersion: 1,
  ownedEntities: [
    "crm.client",
    "crm.contact",
    "crm.interaction",
    "crm.segment_membership",
    "crm.duplicate_candidate",
  ],
  referencedSharedEntities: [
    "workspace.member",
    "crm.opportunity",
    "project",
    "contract",
    "invoice",
    "communication",
  ],
  commands: [
    { id: "create_client", permission: "client.manage", sideEffect: "write" },
    { id: "update_client", permission: "client.manage", sideEffect: "write" },
    { id: "archive_client", permission: "client.manage", sideEffect: "write" },
    { id: "upsert_contact", permission: "client.manage", sideEffect: "write" },
    {
      id: "record_interaction",
      permission: "client.manage",
      sideEffect: "write",
    },
    { id: "assign_owner", permission: "client.manage", sideEffect: "write" },
    {
      id: "propose_duplicate_merge",
      permission: "crm.duplicate.propose",
      sideEffect: "protected-write",
    },
    {
      id: "merge_duplicates",
      permission: "crm.duplicate.merge",
      sideEffect: "protected-write",
    },
  ],
  queries: [
    { id: "search_clients", permission: "client.read" },
    { id: "get_client_360", permission: "client.read" },
    { id: "list_clients_by_segment", permission: "client.read" },
    { id: "find_duplicate_clients", permission: "crm.duplicate.propose" },
  ],
  deterministicRules: [
    "duplicate-score",
    "segment-membership",
    "relationship-health",
  ],
  kpis: [
    "active-clients",
    "at-risk-clients",
    "dormant-clients",
    "open-duplicates",
  ],
  permissions: [
    "client.read",
    "client.manage",
    "crm.duplicate.propose",
    "crm.duplicate.merge",
    "building_block.read",
    "building_block.configure",
    "building_block.approve",
    "building_block.suspend",
  ],
  aiTools: [
    { name: "search_clients", permission: "client.read", sideEffect: "read" },
    { name: "get_client_360", permission: "client.read", sideEffect: "read" },
    {
      name: "list_clients_by_segment",
      permission: "client.read",
      sideEffect: "read",
    },
    {
      name: "summarize_client_relationship",
      permission: "client.read",
      sideEffect: "read",
    },
    {
      name: "list_inactive_clients",
      permission: "client.read",
      sideEffect: "read",
    },
    {
      name: "find_duplicate_clients",
      permission: "crm.duplicate.propose",
      sideEffect: "read",
    },
    {
      name: "explain_client_health",
      permission: "client.read",
      sideEffect: "read",
    },
    {
      name: "list_client_opportunities",
      permission: "opportunity.read",
      sideEffect: "read",
    },
    {
      name: "list_client_projects",
      permission: "project.manage",
      sideEffect: "read",
    },
    {
      name: "list_client_contracts",
      permission: "contract.manage",
      sideEffect: "read",
    },
    {
      name: "list_client_invoices",
      permission: "finance.read",
      sideEffect: "read",
    },
    {
      name: "propose_client_update",
      permission: "client.manage",
      sideEffect: "propose",
    },
    {
      name: "propose_duplicate_merge",
      permission: "crm.duplicate.merge",
      sideEffect: "propose",
    },
  ],
  events: [
    { name: "client.created", direction: "emitted" },
    { name: "client.updated", direction: "emitted" },
    { name: "client.archived", direction: "emitted" },
    { name: "contact.created", direction: "emitted" },
    { name: "interaction.recorded", direction: "emitted" },
    { name: "owner.assigned", direction: "emitted" },
    { name: "client.segment_changed", direction: "emitted" },
    { name: "duplicate.detected", direction: "emitted" },
    { name: "duplicate.merge_proposed", direction: "emitted" },
    { name: "duplicate.merged", direction: "emitted" },
  ],
  integrationPoints: ["ask-flow", "audit", "module-registry"],
  seedDataProfile: "northstar-creative-crm-v1",
  supportedUiStates: [...BUILDING_BLOCK_UI_STATES],
  migrationVersion: "20260906000100",
  testRequirements: [
    "recommendation-rules",
    "invalid-ai-rejection",
    "configuration-schema",
    "dependency-enforcement",
    "activation-approval",
    "workspace-isolation",
    "permissions",
    "rls",
    "seed-idempotency",
    "six-ui-states",
    "ask-flow-evidence",
    "audit-events",
  ],
};
